### ISSUE TITLE
Topic review width is not always 98%

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#11]
The content above the topic review sometimes prevents it from displaying the full width available (theme based on denim theme - firefox browser).

We need to clear the above floating elements.

```
{# begin {templatelocation} #}

</form>

{topic_review}

<!-- BEGIN topic_review -->
<div style="clear:both;"></div>
<div class="uk-grid uk-margin-large-top" style="clear:both;">
    <div class="uk-width-1-1">
        <hr{xhtml}>
        <iframe class="uk-align-center" src="{site_url}/forum/viewtopic.php?mode=preview&amp;showtopic={topic_id}&amp;onlytopic=1&amp;lastpost=true" height="300" width="98%"></iframe>
        <hr{xhtml}>
    </div>
</div>

<!-- END topic_review -->

{# end {templatelocation} #}
```

Does someone have this issue?

**Comment by eSilverStrike** [comment]
Yes I notice that before and I believe I fixed this issue with commit 496ca7146697808778de01b43d445ccbf6b65de4

It had to do with the empty captcha div if I remember correctly.
