### ISSUE TITLE
Tooltip for topic listing with theme based on denim theme is display badly

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#14]
@dengenxp  When using a theme with theme_default set to denim, the tooltip for topic listing is not formatted and is display badly

**Comment by hostellerie** [comment]
@dengenxp @eSilverStrike see demo on this page http://geeklog.fr/forum/index.php?forum=1

**Comment by eSilverStrike** [comment]
The forum uses COM_getTooltip from Geeklog to display tooltips. I think this may be a problem with your Geeklog theme as it seems to be working fine on other themes that have the theme default set to denim. (like geeklog.net).

Take a look and let me know if you have any more info to add.
