### ISSUE TITLE
Member List displays the banned users

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#18]
Banned users are include in the list of active users on forum/memberlist.php

**Comment by eSilverStrike** [comment]
Lots of bugs on this page it seems...

It also looks like the Site Members count listed at the top is off. Mine lists more than the actual number of users on the site.

I also see Sorting by posts is off. It looks like it works but on my site when I sort by posts there is the odd user in the list that isn't in the right position. I see users with 0 posts ahead of users with 1 post.

Finally clicking on last post button shows a page with the posts listed by with an incorrect title of "Last 10 Forum Posts by Admin" and I wasn't viewing the admin's last posts.
