### ISSUE TITLE
Links to last post true not honored or not displayed

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#20]
On forum index page the links to last post do not scroll to the last post on the topic page 
and on a specific forum index there is no link to go to the last post

**Comment by hostellerie** [comment]
In plugins/forum/denim/topic.thtml change 
`<a id="#{topic_post_id}"></a> {# topic post link jump point #}`
to
`<a id="{topic_post_id}"></a> {# topic post link jump point #}`
solved the first issue

**Comment by hostellerie** [comment]
In plugins/forum/denim/topiclisting.thtml change 

```
    <td>
        {LANG_BY}{lastposter}<br{xhtml}>
        {lastdate}
    </td>
```

to

```
    <td>
        {LANG_BY}{lastposter}<br{xhtml}>
        <a href="viewtopic.php?showtopic={topic_id}&amp;lastpost=true#{lastpostid}">{lastdate}</a>
    </td>
```

solved the second issue

**Comment by eSilverStrike** [comment]
Thanks for the fixes Ben
