### ISSUE TITLE
Buttons (bold,italyc, url...) do not work properly with Denim theme

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#21]
When you click the button, the bbcode is added like is suppose to be but an opening tag is also added at the end of the text. You can reproduce this on geeklog demo site

I see a difference in creatopic.js maybe it is related

```
eval('document.forumpost.addbbcode' + butnumber + '.className ="uk-button"'); // Used for uikit themes
// eval('document.forumpost.addbbcode' + butnumber + '.value ="' + buttext.substr(0,(buttext.length - 1)) + '"'); // Used by normal theme
```

**Comment by eSilverStrike** [comment]
I seem to remember this happens only in IE... Did you try it in Firefox or Chrome?

**Comment by hostellerie** [comment]
I can reproduce the issue on IE11 and FF 45. Chrome is OK

**Comment by eSilverStrike** [comment]
Okay BBcode buttons should work like:
- Select text and hit bbcode button the text is surrounded by proper open and close bbcodes. BBCode button returns to proper not active state
- Hit bbcode button with no selected text, bbcode button becomes active and open bbcode is inserted into text. When button hit again close bbcode is inserted into text and button returns to non active state.

Current problems:
- When selecting text and hitting bbcode button the proper bbcodes are added to the text but the button remains active and does not return to non active state
- The very first time a bbcode button is pressed both the open and closed bbcodes are added. should just be an open bbcode (unless text is selected)

For some reason the javascript (located here \public_html\forum\javascript\denim\createtopic.js) cannot reset the class of the buttons using this code:
```
eval('document.forumpost.addbbcode' + butnumber + '.className ="uk-button"');
```
Is the uikit javascript preventing it and keeping the class of the button "uk-button uk-active"?

**Comment by eSilverStrike** [comment]
@dengenxp do you have any ideas on how to fix this?

**Comment by dengenxp** [comment]
Fixed with change set 8ef0eb7
It's OK?

**Comment by eSilverStrike** [comment]
Thanks. I found one more issue though after testing

The only problem I see now (for both the default and denim forum templates) is if I put the cursor in the middle of some text (not selecting any text) and then hit one of the bbcode buttons the open bbcode  gets put at the end of the message and not where the cursor was.

**Comment by dengenxp** [comment]
Fixed with change set 3dbc763 tentatively.
I tested this fix only with Firefox and Chrome on Linux. Perhaps it will not work properly with IE on Windows yet.

**Comment by eSilverStrike** [comment]
Just tested and it does work on Firefox on Windows. It does not work with IE9 and lower and Edge on Windows. It appears to be a bug with IE as support was added in IE10.

There are workarounds which I tried but couldn't get them to work:

https://github.com/eligrey/classList.js

and 

```
if (button.classList) {
   button.classList.remove("uk-active");
} else {
    button.className = x.className.replace(/\buk-active\b/g, ""); // For IE9 and earlier
}


if (button.classList) {
    button.classList.add("uk-active");
} else {
    button.className = "uk-button uk-active"; // For IE9 and earlier
}
```

Maybe you will have better luck?

**Comment by dengenxp** [comment]
I tested change set 3dbc763 on Windows10. It worked properly with Firefox, Chrome, IE11 and Edge.

**Comment by eSilverStrike** [comment]
So on Windows with the Edge browser the bbcode buttons are active and not active as required for the denim theme? The bbcodes get inserted into the text fine (which is the most important part) but I notice that the actual buttons are not active (or active) when they should necessarily be. 

It does work fine in Firefox and Chrome for me. From my understanding the Edge browser has issues with classlist, or maybe it is a problem on my end with Edge.

**Comment by dengenxp** [comment]
It works fine with the Edge browser for me. The actual bbcode buttons are active (or not active) as required.

**Comment by eSilverStrike** [comment]
Okay good. Not sure what is wrong with mine then. I will close the issue and only reopen if someone else has the same problem.
