### ISSUE TITLE
Forum for logged-in users displays 404 error page

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#25]
Instead of displaying a 404 error page when the users are not logged-in and try to access to a private forum, could we have a login page ?

**Comment by hostellerie** [comment]
Changing from forum_chkUsercanAccess() to forum_chkUsercanAccess(true) line 61 on forum/index.php file solved my issue

```
//Check is anonymous users can access - and need to be signed in
forum_chkUsercanAccess(true);
```

**Comment by eSilverStrike** [comment]
That fix doesn't work as it creates an issue for forums that don't require registration to view.

Your talking about a situation where the forum doesn't require registration to view right but some  forum categories are for private user groups only?

The reason for the 404 error is that so search engines and hackers/spammers don't know about that forum category.

I do understand your reasoning though as a user who has access to the forum and happens to be logged out will get confused if he tries to access the forum from a bookmark or forum email notification.

**Comment by eSilverStrike** [comment]
Okay after thinking it over I figured it was better to allow users who don't realize they are not logged in and have access to the forum a more appropriate message.

This does allow people snooping around to figure out that the private forum does exist but nothing further.
