### ISSUE TITLE
Editing a Forum Topic with no replies results in center block showing a reply

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/forum#55]
Forum Center block shows a "Last Reply" as the original author after the post was edited by Admin.  Note this forum topic only has the 1 post.

Example:

Started By mike, » 2018/05/14 04:09pm 
Last reply by: mike » 2018/05/14 04:09pm Replies:0 

It should just say:

Replies:0

**Comment by mystralkk** [comment]
I cannot reproduce this bug.

**Comment by eSilverStrike** [comment]
Related to #66. Should be fixed with the commit c8f3d188f0023ccb759013af2b2dc5109fe17a5d

It dealt with a resync issue.
