### ISSUE TITLE
Add Invisible reCaptcha Support

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/forum#56]
Supported in recaptcha Plugin 1.2.0 which ships with Geeklog v2.2.0

**Comment by eSilverStrike** [comment]
I have added the invisible_captcha template variables to the forum templates and updated the recaptcha plugin.

Unfortunately I keep getting an javascript error about the  form.submit() function does not exist and I am not sure why….

To test you will have to enable the invisible captcha for the forum in the configuration as it defaults to reCAPTCHA V2

**Comment by mystralkk** [comment]
With the Denim theme on Google Chrome, I cannot reproduce this bug.  Invisible reCAPTCHA seems to work fine.

**Comment by eSilverStrike** [comment]
Seems to be working now. Tested on Geeklog.net
