### ISSUE TITLE
I make column 'subtype' in _topic_assignments

### ISSUE THREAD

**Issue by P2Tera** [Geeklog-Plugins/forum#69]
Geeklog 2.2.1 new install
Forum2.9.4 install
Forum Administration
 Add Category  save

E_USER_ERROR(256) - 1054: Unknown column 'subtype' in 'where clause' @ /virtual/kawachi/dwn/geeklog/system/databases/mysqli.class.php line 468
Call Stack
#	Function	File	Line
1	trigger_error	.../dwn/geeklog/system/databases/mysqli.class.php	468
2	dbQuery	.../dwn/geeklog/system/databases/mysqli.class.php	588
3	dbDelete	.../dwn/geeklog/system/lib-database.php	258
4	DB_delete	.../dwn/geeklog/system/lib-topic.php	811
5	TOPIC_saveTopicSelectionControl	.../dwn/geeklog/public_html/admin/plugins/forum/boards.php	117
 array(3) {
  ["sql"]=>
  string(92) "DELETE FROM gl2_topic_assignments WHERE type = 'forum' AND id = '1' AND subtype = 'category'"
  ["ignore_errors"]=>
  int(0)
  ["result"]=>
  bool(false)
}

I make column 'subtype' in gl2_topic_assignments.

**Comment by eSilverStrike** [comment]
Thanks. The issue was with Geeklog and new installs (upgrade added the missing column). The fix has now been applied to the latest code in the Geeklog repository.
