### ISSUE TITLE
Size and List BBCode is not working

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/forum#71]
Seems to be not working for uikit2 templates. Not sure about others.

The [size=15]… [/size] code doesn't even get removed from the text

**Comment by eSilverStrike** [comment]
[list] BBCode seems not to work (bbcode is not even parsed out of post text) on Geeklog.net either. Double check all BBCode.

**Comment by eSilverStrike** [comment]
May be related to #73

**Comment by mystralkk** [comment]
Cannot reproduce this bug with the Denim theme.

**Comment by eSilverStrike** [comment]
Okay things seem to be working a lot better. Thanks.

One thing I notice is that any BBCode inside of a font color change or font size change doesn't get applied.

Where as for any other bbcode like list or bold you can have bbcode within bbcode.

Here is an example of my test code that I put in a forum post where you can see the larger font size does not get changed to a different color within the size change:

```
[QUOTE][u]Quote by: Laugh[/u][p]Testing bbcode

[list]
[*]List 1
[*]List 2
[*]List 3
[/list]

This is a test.

Thi[b]s[u] is [/u]a t[/b]est.
This is a test.

T[u]his is a te[/u]st.
Th[size=18]is [color=red]is [/color]a te[/size]st.

Thi[color=red]s is a t[/color]e[color=blue]st[/color]. :twisted: [/p][/QUOTE]

This i[color=red]s a reply to bbc[/color]ode

Th[color=red]is[color=#000] is l[/color]ot[size=18]s [u]of c[/u]o[/size]lor and thi[/color]ngs.

[list]
[*]List 1
[*]Lis[u]t 2[/u]
[*]Li[color=red]st [u]3[/u][/color]
[/list]

[code]
a=b;
b=c;
echo a;
 [/code]

[url=https://www.geeklog.net]Geeklog[/url]

[url]https://www.geeklog.net[/url]
```

**Comment by eSilverStrike** [comment]
@mystralkk Found another issue as well. Looks like the [code] bbcode  is not working either in text or html mode. 

https://www.geeklog.net/forum/viewtopic.php?forum=6&showtopic=60248

**Comment by eSilverStrike** [comment]
So everything looks to be working except for any bbcode that falls within a color or size tags (ie [color=red] or [size=18]). While the initial tag themselves gets converted any bbcode tags inside a color or size tag does not. Example here will show the red text but every other bbcode does not get parsed and appears in the actual forum post.

`Th[color=red]is is lot[size=18]s [u]of c[/u]o[/size]lor and thi[/color]ngs.`
