### ISSUE TITLE
Combination of bbcode causes parser to error

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/forum#73]
Got the following error on a forum post someone submitted:

E_SYNTAX(0) - Call to a member function hadCloseTag() on null @ /home/private/plugins/forum/include/bbcode/stringparser_bbcode.class.php line 1818

The bbcode they had at the end of the post caused the error. Here it is:

```
Some text they wrote 
[size=7][/size]C[color=darkred][/color][list]alifornia
```

**Comment by mystralkk** [comment]
Fixed with change set e62579d.
