### ISSUE TITLE
BBCode appears in the Search Results for Forum Posts

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/forum#78]
Not sure if related to #71.

BBCode is not stripped from the search results so for example you will see

[QUOTE][u]Quote by: Anonymous[/u][p] blah blah blah....

**Comment by mystralkk** [comment]
This issue has nothing to do with issue #71.  The problem is in the Search class since it doesn't allow plugins to modify search results after executing query.
